app:
  jwt_secret: "23347$040412"
  run_mode: "debug"
  page_size: 10


server:
  http_port: 8039
  read_timeout: 60
  write_timeout: 60

mysql:
  user: "rey"
  password: "1"
  host: "121.40.151.71:3306"
  db_name: "mblog"
  table_prefix: "blog_"
  max_open_conns: 200
  max_idle_conns: 50
  max_life_time: 3600 # 60 * 60s = 3600s
