apiVersion: v1
kind: Pod
metadata:
  name: greeter
  labels:
    plan: dev
  # namespace:
spec:
  containers:
    - name: greeter
      image: tinklerey/greeter
      resources:
        limits:
          memory: "200Mi"
          cpu: "500m"
        #requests:
        #memory: "100Mi"
      #command: ["stress"]
      #args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
